gestionmateriales/gestionmateriales/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gestionmateriales.Models.GestionMateriales;
using gestionmateriales.Models;

namespace gestionmateriales.Controllers
{
    public class ComprasController : Controller
    {
        OficinaTecnicaEntities db = new OficinaTecnicaEntities();

        // GET: Compras
        [Authorize(Roles = "administrador, oficinatecnica, rectoria")]
        [Route("/Compras")]
        [HttpGet]
        public ActionResult Index()
        {
            OficinaTecnicaEntities db = new OficinaTecnicaEntities();
            List<Material> materiales = db.materiales.Where(x => x.hab && x.stockActual <= x.stockMinimo).ToList();
            return View("Index", materiales);
        }
        
        //GET: AprobarOP
        [Authorize (Roles = "administrador, oficinatecnica")]
        [Route("/AprobarOP")]
        [HttpGet]
        public ActionResult AprobarOP()
        {
            return View();
        }

        //POST: AprobarOP
        [HttpPost]

        public ActionResult AprobarOP(ComprasViewModels compra)
        {
            //TODO: falta implementar el mergeo de los las ordenes de pedido con el stock real
            // es decir que se tiene que contrastar lo que se necesita con lo que hay en deposito
             //var items = from op in db.ordenPedido 
             //            join i in db.ItemOP on op.idOrdenPedido equals i.idOrdenPedido
             //            where op.fecha > compra.fechaInicio && op.fecha < compra.fechaFin
             //            group op by i.idMaterialB into materialGroup
             //            select new {materialGroup., 
             //                        i.cantidad, 
             //                        getStockActualById(i.idMaterial),
             //                        getStockActualById(i.idMaterial) - i.cantidad
             //            };

            return View();                         
        }
    }
}

gestionmateriales/gestionmateriales/Controllers/ConstruccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace gestionmateriales.Controllers
{
    public class ConstruccionController : Controller
    {
        // GET: Contruccion
        [Authorize(Roles = "administrador, oficinatecnica, deposito, rectoria")]
        [Route("/Construccion")]
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

gestionmateriales/gestionmateriales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Principal - OT</title>
    
    <!--JQuery-->
    <!---script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></!--script-->
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>

    <!-- Bootstrap -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"-->
    <!--script-- src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></!--script-->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>

    <!--Scrips Varios-->
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <!--Datatables-->
    <link rel="stylesheet" type="text/css" href="~/Scripts/Datatables/datatables.css" />
    <script type="text/javascript" src="~/Scripts/Datatables/datatables.min.js"></script>

    <!--Notitify-->
    <script type="text/javascript" src="~/Scripts/notify.min.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> Documentos<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Orden de Trabajo de Aplicación", "Index", "OrdenTrabajo")</li>
                            <li>@Html.ActionLink("Orden de Pedido", "Index", "OrdenPedido")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Trabajo Práctico", "Index", "Construccion")</li>
                            <li>@Html.ActionLink("Donación", "Index", "Construccion")</li>
                            <li>@Html.ActionLink("Sobrante", "Index", "Construccion")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Stock<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Ingreso", "Sumar", "Stock")</li>
                            <li>@Html.ActionLink("Egreso", "Restar", "Stock")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Compras<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Materiales a Comprar", "Index", "Compras")</li>
                        </ul>
                    </li>
                    <li><a href="~/Material/Index"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Materiales</a></li>
                    <li><a href="~/Proveedor/Index"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Proveedores</a></li>
                    <li><a href="~/Personal/Index"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Personal</a></li>
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
            @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ET N°12 DE 1 Libertador General José de San Martín</p>
        </footer>
    </div>
</body>
</html>

gestionmateriales/gestionmateriales/Views/Shared/_LoginLayout.cshtml
@{
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no" name="viewport" />
    <meta content="PPType" name="author" />
    <meta content="#ffffff" name="theme-color" />
    <title>Login - OT</title>
    <link href="~/Scripts/Semantic/semantic.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/Semantic/default.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/Semantic/pandoc-code-highlight.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/Semantic/semantic.min.js"></script>
</head>
<body>
        @RenderBody()
</body>
</html>